language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t lokeshkd/docker-react -f ./frontend/Dockerfile.dev ./frontend/.

scripts:
        #- docker run docker-react npm run start -- --coverage
        - docker run -e CI=true lokeshkd/docker-react npm run test
